/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITokenBoundAccount } from "./ITokenBoundAccount";
export type { ITokenBoundAccountProxy } from "./ITokenBoundAccountProxy";
