/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IPermittedNFTs,
  IPermittedNFTsInterface,
} from "../../../contracts/interfaces/IPermittedNFTs";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_nftContract",
        type: "address",
      },
    ],
    name: "getNFTPermit",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPermittedNFTs__factory {
  static readonly abi = _abi;
  static createInterface(): IPermittedNFTsInterface {
    return new Interface(_abi) as IPermittedNFTsInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IPermittedNFTs {
    return new Contract(address, _abi, runner) as unknown as IPermittedNFTs;
  }
}
