/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITokenBoundAccount__factory } from "./ITokenBoundAccount__factory";
export { ITokenBoundAccountProxy__factory } from "./ITokenBoundAccountProxy__factory";
