/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ILendingPool } from "./ILendingPool";
export type { ILendingStake } from "./ILendingStake";
export type { IMarketplace } from "./IMarketplace";
