/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface IMarketplaceInterface extends Interface {
  getFunction(nameOrSignature: "closeItem" | "makeItem"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "closeItem",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "makeItem",
    values: [AddressLike, BigNumberish, AddressLike, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "closeItem", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "makeItem", data: BytesLike): Result;
}

export interface IMarketplace extends BaseContract {
  connect(runner?: ContractRunner | null): IMarketplace;
  waitForDeployment(): Promise<this>;

  interface: IMarketplaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeItem: TypedContractMethod<[_itemId: BigNumberish], [void], "nonpayable">;

  makeItem: TypedContractMethod<
    [
      _nft: AddressLike,
      _tokenId: BigNumberish,
      _paymentToken: AddressLike,
      _price: BigNumberish,
      _beneficiary: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeItem"
  ): TypedContractMethod<[_itemId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "makeItem"
  ): TypedContractMethod<
    [
      _nft: AddressLike,
      _tokenId: BigNumberish,
      _paymentToken: AddressLike,
      _price: BigNumberish,
      _beneficiary: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
