/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { LendingPool } from "./LendingPool";
export type { LendingStake } from "./LendingStake";
